version: "2"
linters:
  default: standard
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
    - golines
    - swaggo
run:
  timeout: 5m
  issues-exit-code: 0
severity:
  default: error
